### ISSUE TITLE
the base64 url encode generate a different string 

### ISSUE THREAD

**Issue by sujayran** [Thalhammer/jwt-cpp#122]
`jwt::base::encode<jwt::alphabet::base64url>("Cluster1-NF");`

generate `Q2x1c3RlcjEtTkY%3d`  why we have `%3d` appended at last, ideally, it should have been for URL SAFE `Q2x1c3RlcjEtTkY`

Thanks for the Input

**Comment by Thalhammer** [comment]
Because a valid base64 string is required to have padding at the end so that the urldecoded version is a multiple of 4 bytes.
%3d is the url representation of the '=' character which is the base64 padding character.
While most libraries will handle strings with missing padding just fine, it is technically not a valid base64 string.
If you dont want the padding copy paste the alphabet and replace he "fill" function to return an empty string instead.

**Comment by sujayran** [comment]
Thanks for the quick response.

**Comment by prince-chrismc** [comment]
There's also a trim helper

https://github.com/Thalhammer/jwt-cpp/blob/b21d80c22e143733d40c5d941ea619930c02894a/include/jwt-cpp/base.h#L77
