### ISSUE TITLE
std::is_constructible<value_type, integer_type> fails for picojson

### ISSUE THREAD

**Issue by NPellet** [Thalhammer/jwt-cpp#129]
Seems like the assertion support_as_integer, at least in the latest version I've checked out from the repo.

Seems to fail at
```c++
std::is_constructible<value_type, integer_type>::value
```

(By the way, this describes that picojson::value can be constructed by int64_t, however, the static assertion is: 
```"traits must provide `integer_type as_int(const value_type&)`"``` which does not correspond to the actual check (at least this one))

For it to work, one has to define PICOJSON_USE_INT64:

Source

```c++
#ifdef PICOJSON_USE_INT64
  explicit value(int64_t i);
#endif
```

which, I think, could be included in jwt.h

**Comment by NPellet** [comment]
Oh wait, it is defined.
However I included picojson.h before you for another purpose.

Ok well then it's not a bug, but might be worth mentionning in the doc.

**Comment by prince-chrismc** [comment]
Just to confirm the issue is that the default picojson traits relies on the `int64_t` which was missing from your include order?

**Comment by NPellet** [comment]
Yes, I was missing this definition:

```#ifndef PICOJSON_USE_INT64
#define PICOJSON_USE_INT64
#endif```

If picojson ships with it's own definition, you could check if it exists, and if PICOJSON_USE_INT64 also exists, and if not, throw an error or smth

like:

```#if defined(picojson_h) && !defined(PICOJSON_USE_INT64)
// report an error more clearly
#endif
```

Also, I stand by my initial point that the is_constructible static check doesn't relate well to the reported error (as_int is missing)

**Comment by prince-chrismc** [comment]
I am surprised that is happening since we force that macro on https://github.com/Thalhammer/jwt-cpp/blob/5b20cd637aa2760812c544bb2cf20087d0a01ec7/include/jwt-cpp/jwt.h#L5-L7
which should be more than enough (there's only `#ifdef` checks)

Do you have two `picojson` file in your include directories? Something like
- `/usr/local/include/picojson.h`
- `/usr/local/include/picojson/picojson.h` ◀️ This is what we install/distribute

If your repo is public, I like to take a peak since there is something interesting going on.

***

I apologize, I did not 100% understand your first post, English is my second language. So I missed the suggestion you made...

> the is_constructible static check doesn't relate well to the reported error (as_int is missing)

I absolutely agree 💯 Template unrolling on < gcc-10  or < clang- 9 is nearly impossible so I added static asserts to help _guide_ users to finding the problem.

https://github.com/Thalhammer/jwt-cpp/blob/5b20cd637aa2760812c544bb2cf20087d0a01ec7/include/jwt-cpp/jwt.h#L1713-L1715

If you care to craft another static assertion for the `picojson_traits` to validate the `int64_t` is enabled, I'd love to merge that in 😃

**Comment by Thalhammer** [comment]
Just to add a side note an what I think was going on:
Yes we do force PICOJSON_USE_INT64, however this obviously only applies to everything included past jwt-cpp. Normally this is always the case since we include picojson right after it. The Problem is if you happen to already use picojson in your project and included it before jwt-cpp there is no PICOJSON_USE_INT64 defined for that unit. Picojson also has include guards, so the second include we do effectively is a noop.

IMHO if you use picojson you should always enable PICOJSON_USE_INT64, since it makes working with non float values a lot safer and not to mention easier, but thats obviously up to the user to decide.

Probably a warning to tell people to swap around the includes would make more sense.
