### ISSUE TITLE
[bug] Wunused-private-field with Clang

### ISSUE THREAD

**Issue by Carbenium** [Thalhammer/jwt-cpp#134]
**Describe the bug**
The following warning is shown during build:
```
/tmp/cirrus-ci-build/dep/jwt-cpp/include/jwt-cpp/jwt.h:1177:20: warning: private field 'md' is not used [-Wunused-private-field]
                        const EVP_MD* (*md)();
```

**Desktop:**
 - OS: FreeBSD 12.2
 - Compiler clang 10.0.1
 - Version 0.5.0 (b45bc9994d8087c5ba7aa1f1588302f04ae84c83)

**Comment by prince-chrismc** [comment]
Thanks for reporting the warning, that's always suspicious. 🤔 

Typically the `md` is used to setup the "digest context" but in the case of `eddsa` it uses https://github.com/Thalhammer/jwt-cpp/blob/b45bc9994d8087c5ba7aa1f1588302f04ae84c83/include/jwt-cpp/jwt.h#L1091
and the [man pages](https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestSignInit.html) say
>Ed25519 and Ed448
Support no digests (the digest type must be NULL)

This might be some copy paste since they do set it to `EVP_sha256`
