### ISSUE TITLE
Eliminate deprecations warnings with OpenSSL 3

### ISSUE THREAD

**Issue by NFM-8** [Thalhammer/jwt-cpp#150]
Currently, build against OpenSSL 3.0.0 release candidate fails because many deprecated OpenSSL functions is used.

For more information, see https://www.openssl.org/docs/manmaster/man7/migration_guide.html

**Comment by Thalhammer** [comment]
Ahhhh what happened to OpenSSL 2.x ?
Anyway thanks for bringing it up, I hadn't even realized that OpenSSL 3 was a thing.
We will ofc support it. That said it might take a while to set up a dev environment that supports such recent versions.

**Comment by prince-chrismc** [comment]
Tests passing 👍 https://github.com/Thalhammer/jwt-cpp/actions/runs/1127485043

In time we'll fix the deprecation warnings

**Comment by Thalhammer** [comment]
I don't think we should close this. For many people (including me) a deprecation warning actually breaks the build, since they build with Werror on. Sure those could ignore the warning for jwt-cpp, but I don't feel like that's a valid recommendation. I'd rather only close this if we either ignore the warnings in our code or (much better) fix them.

**Comment by prince-chrismc** [comment]
That's reasonable! I read "support" and that was added, but yes we can go the extra mile
