### ISSUE TITLE
[Feature] Provide more supported traits

### ISSUE THREAD

**Issue by prince-chrismc** [Thalhammer/jwt-cpp#174]
Currently we only offer the `picojson_traits` that is also the default. 

It would be ideal to provide all the known support traits
1. It's better for consumers
2. It's less duplication 
3. easier to maintain

***

The proposal would be to have a header file for each support library

```
include/
├─ jwt-cpp/
│  ├─ jwt.h
│  ├─ base.h
│  ├─ traits/
│  │  ├─ picojson.h
│  │  ├─ nlohmann_json.h
│  │  ├─ jsoncons.h
│  │  ├─ boost_json.h
```

❓ Do we provide default specializations? This requires a `define` to make sure there's only one included
❓ Does this require a CMake option?
❓ What about badges for tested version?

**Comment by Thalhammer** [comment]
> Do we provide default specializations? This requires a define to make sure there's only one included
I don't think we can pull out the default support for picojson without breaking existing code. If so we would have to atleast make it optional (i.e. a compile options thats off by default). Or wait a version and mark it deprecated for a while.

> Does this require a CMake option?
As long as we only add extra headers and stuff in there I dont think it needs one. If you dont include the header nothing changes and if you do, its pretty obvious that you need the respective json library available.

> What about badges for tested version?
Shouldn't be a big issue, since we wouldn't need to test every combination between ssl and json. Testing every json against a single ssl implementation should be fine, as long as the ssl version does not break.

**Comment by prince-chrismc** [comment]
> I don't think we can pull out the default support for picojson without breaking existing code.

I agree! thus far I have been able to maintain it as the default with the same cmake/compile option

> As long as we only add extra headers and stuff in there I dont think it needs one.

The challenge is when the consumer links to multiple defaults then they will get incorrect results (since it creates the same symbols and links to the work json implementation)

***

As for file structures, I have this:

```
include/
├─ jwt-cpp/
│  ├─ jwt.h
│  ├─ base.h
│  ├─ traits/
│  │  ├─ kazuho-picojson/
│  │  │  ├─ traits.h
│  │  │  ├─ defaults.h
│  │  ├─ nlohmann-json/
│  │  │  ├─ traits.h
│  │  │  ├─ defaults.h
│  │  ├─ danielaparker-jsoncons/
│  │  │  ├─ traits.h
│  │  │  ├─ defaults.h
│  │  ├─ boost-json/
│  │  │  ├─ traits.h
│  │  │  ├─ defaults.h
```

I opted for a seperate defaults file so
- multiple traits could be used if desired
- the defaults could be auto generated [ref](https://github.com/prince-chrismc/jwt-cpp/blob/provide-traits/include/jwt-cpp/traits/defaults.h.mustache)
