### ISSUE TITLE
Partial claim verification

### ISSUE THREAD

**Issue by sirzooro** [Thalhammer/jwt-cpp#212]
**Describe the impediment**
RedHat SSO allows configuration of roles for given service. When service gets its JWT token from SSO, it contains following claim with these roles:

```js
"resource_access": {
   "my-service": {
     "roles": [
       "foo",
       "bar",
       "baz"
     ]
   }
 },
```

**Trying to obtain**
I need to verify that service called "my-service" has role "bar", and ignore any other roles present in this claim. I found example where custom claim value is checked against JSON object, but this is not exactly my case - I need to check for this JSON structure ("resource_access", "my-service", "roles" elements) and verify that roles array contains proper element. Is there a way to do this using `.with_claim("resource_access", ...)`? Or do I have to use `verifier.verify()` first, and then manually extract and verify this claim piece by piece?

**Desktop:**
 - OS: RedHat 8
 - Compiler g++ 10.3.1
 - Version jwt-cpp v0.6.0

**Comment by prince-chrismc** [comment]
Hmm, the docs are lacking in this area, thanks for bringing this up!

When I built on top of jwt-cpp (v0.5.0), I had two application requirements
- valid JSON schema
- granted correct roles

The first was easy, I was already using RapidJSON to do that.
The second, before the verifier API, I just accessed the nested private claim (which I knew was there from the JSON schema) and looked up my two required roles.

We now have https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/include/jwt-cpp/jwt.h#L3012 so that might help

However only the "top level" claims are passed to the verifier, https://github.com/Thalhammer/jwt-cpp/blob/master/include/jwt-cpp/jwt.h#L3299

That's likely the best way to

> verify this claim piece by piece

Hopefully that helps answer your questions 🤞

**Comment by sirzooro** [comment]
I have noticed one more issue: error message for exception (returned by `what()`) thrown after `jwt::error::token_verification_error::claim_value_missmatch` error is reported does not include claim name which did not pass validation. This name would be useful during debugging of connection issues caused by incorrect token claims. This issue probably also applies to other generic claim verification errors.

**Comment by Thalhammer** [comment]
> error is reported does not include claim name which did not pass validation

I agree that this would be helpfull, but thats hard to do. The way it works is that jwt-cpp builds a `std::error_code` and throws a `std::system_error` containing the error code. While this is usually a good design because it provides a very consistent and stl friendly interface, it makes adding runtime information to the message/exception near impossible. `std::error_code` only stores a int error code and a pointer to an error category. However it does not own the category (it needs to be valid for the lifetime of the error_code, that usually means a static singleton). If the message is requested it calls a method on the category passing the error code, which than returns a (also static) c style string. Including runtime info usually means some kind of hack or a memory leak.

**Comment by sirzooro** [comment]
> > error is reported does not include claim name which did not pass validation
> 
> I agree that this would be helpfull, but thats hard to do. The way it works is that jwt-cpp builds a `std::error_code` and throws a `std::system_error` containing the error code. While this is usually a good design because it provides a very consistent and stl friendly interface, it makes adding runtime information to the message/exception near impossible. `std::error_code` only stores a int error code and a pointer to an error category. However it does not own the category (it needs to be valid for the lifetime of the error_code, that usually means a static singleton). If the message is requested it calls a method on the category passing the error code, which than returns a (also static) c style string. Including runtime info usually means some kind of hack or a memory leak.

Custom exception class derived from `std::system_error` could have extra field to store claim name, and some method like `claim_name()` to get it. This would enough for me to build meaningful log message, so you could leave default implementation of `what()`.

**Comment by prince-chrismc** [comment]
> * code from rsa-create.cpp example does not compile - compiler complained about unknown `jwt::claim` type. It compiled after I removed this explicit type cast;

Hmm 🤔 that's very odd.... https://github.com/Thalhammer/jwt-cpp/runs/5156063246?check_suite_focus=true#step:7:10
it's Passing in CI.

> * I had to explicitly specify `jwt::traits::nlohmann_json` as a template parameter in few places. Please provide some `#define` to specify default traits type, it would simplify code a bit;

That explains above, it made for the default choice of picojson!

Did you try including https://github.com/Thalhammer/jwt-cpp/blob/master/include/jwt-cpp/traits/nlohmann-json/defaults.h?
There's no docs so sorry for the confusion. Let me know if that helps

> all jwt-cpp exception types are derived directly from std::system_error. It would be handy if you could use some library-specific base class instead, e.g. jwt::validation_error. This would allow to write bigger block of code, and at the end

This is a really interesting point! Feel free to open a new issue so we can track that idea 🙏

**Comment by prince-chrismc** [comment]
Thank you so much for the feedback, I am glad there was just enough flexibility to keep you moving forward 🚀

**Comment by prince-chrismc** [comment]
Thank you so much! Hopefully in the coming weeks we can fold in your suggestions 🤗

**Comment by JSoet** [comment]
@prince-chrismc 

Sorry to comment on this old issue, I'm just wondering about one thing that you mentioned [here](https://github.com/Thalhammer/jwt-cpp/issues/212#issuecomment-1050467769):
> The first was easy, I was already using RapidJSON to do that.

I was just wondering if this library supports using rapidjson as the json parser using the json traits, I was trying to find some info and found this other issue which seems to suggest it isn't supported: 
https://github.com/Thalhammer/jwt-cpp/issues/96#issuecomment-673352191

But then also found your comment above which seems to suggest that you were using rapidjson? Were you using rapidjson as the parser for jwt-cpp using the traits, or do you just mean you were using it separately just taking the json and parsing it again using rapidjson or something like that?

**Comment by prince-chrismc** [comment]
Ughs 4 jobs ago... 🤔  The later. We used picojson with jwt-cpp and Marshalled the data back and forth to use it with rapidjson for schema validation.

Rapidjson could be used with jwt-cpp, the effort required probably isn't worth it. Its likely just as much work to switch for another json library.

**Comment by JSoet** [comment]
Thanks for the reply, just wanted to check, yeah, we'll just use another library for use with jwt-cpp then.
